### ISSUE TITLE
V(fblog.c) crashes after fblog.c <- contract.vertices(fblog, party.nums) in CHUNK 14 of Chapter3.R

### ISSUE THREAD

**Issue by ZuchaoWang** [kolaczyk/sand#1]
Hi, Kolaczyk,

First, many thanks for this nice book! Below is the issue:

In CHUNK 14 of Chapter3.R
I tried to run V(fblog.c) immediately after fblog.c <- contract.vertices(fblog, party.nums), then it crashed
I also tried summary(fblog.c), it also crashed
The system mentioned that it's igraph.so that crashes
Although the crash is not in your code, but it's related.
Do you know how to fix that?

Below is my R version:
platform       x86_64-pc-linux-gnu  
arch           x86_64  
os             linux-gnu  
system         x86_64, linux-gnu  
status         beta  
major          3  
minor          1.0  
year           2014  
month          03  
day            28  
svn rev        65330  
language       R  
version.string R version 3.1.0 beta (2014-03-28 r65330)
nickname       Spring Dance      

My igraph version is 0.7.1
My sand version is 1.0.2

**Comment by JunlueZhao** [comment]
I am having the same issue. After fblog.c <- contact.vertices(fblog,party.num) Rstudio crashes every time. I've tried it many times.
