### ISSUE TITLE
Installing from Cran is already available

### ISSUE THREAD

**Issue by alfredo203** [kolaczyk/sand#2]
Hi, I was wondering if the package documentation would be updated. Is still showing to install from github because Cran download is not yet released.
```
install.packages("devtools")
library(devtools)
install_github("kolaczyk/sand/sand")
```

I believe the Cran package is available to download with the regular package installing code.
```
install.packages("sand") 
```

By the way thanks for the excellent book!

**Comment by kolaczyk** [comment]
Hi, Alfredo

Thanks for the kind words about our book.  I have Cc'd Gabor regarding your question below.

Eric Kolaczyk

**Comment by gaborcsardi** [comment]
Thanks! I just fixed it.
